CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS texts (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    text_id TEXT UNIQUE NOT NULL,
    author_id TEXT NOT NULL,
    content TEXT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (author_id) REFERENCES users(user_id)
);
CREATE TABLE IF NOT EXISTS invites (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    invite_code TEXT UNIQUE NOT NULL,
    user_email TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS sessions (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    session_token TEXT UNIQUE NOT NULL,
    user_email TEXT NOT NULL,
    session_start TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    session_expiration TIMESTAMP NOT NULL,
    FOREIGN KEY (user_email) REFERENCES users(email)
);
