-- This file contains the initial schema for the database

-- Users table
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    _id TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Invites table
CREATE TABLE IF NOT EXISTS invites (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    invite_code TEXT UNIQUE NOT NULL,
    user_email TEXT NOT NULL
);

-- Sessions table
CREATE TABLE IF NOT EXISTS sessions (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    session_token TEXT UNIQUE NOT NULL,
    user_email TEXT NOT NULL,
    session_start TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    session_expiration TIMESTAMP NOT NULL,
    FOREIGN KEY (user_email) REFERENCES users(email) ON DELETE CASCADE
);

-- Groups table
CREATE TABLE IF NOT EXISTS groups (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    _id TEXT UNIQUE NOT NULL,
    author_id TEXT NOT NULL,
    label TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (author_id) REFERENCES users(_id) ON DELETE CASCADE
);

-- Blocks table
CREATE TABLE IF NOT EXISTS blocks (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    _id TEXT UNIQUE NOT NULL,
    group_id TEXT NOT NULL,
    author_id TEXT NOT NULL,
    label TEXT NOT NULL DEFAULT '',
    content TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (author_id) REFERENCES users(_id) ON DELETE CASCADE,
    FOREIGN KEY (group_id) REFERENCES groups(_id) ON DELETE CASCADE
);

-- Transformations table
CREATE TABLE IF NOT EXISTS transformations (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    _id TEXT UNIQUE NOT NULL,
    group_id TEXT NOT NULL,
    author_id TEXT NOT NULL,
    input_block_id TEXT NOT NULL,
    label TEXT NOT NULL DEFAULT '',
    prompt TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (author_id) REFERENCES users(_id) ON DELETE CASCADE,
    FOREIGN KEY (group_id) REFERENCES groups(_id) ON DELETE CASCADE,
    FOREIGN KEY (input_block_id) REFERENCES blocks(_id) ON DELETE CASCADE
);

-- Transformations output Blocks table
CREATE TABLE IF NOT EXISTS transformation_outputs (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    transformation_id TEXT NOT NULL,
    output_block_id TEXT NOT NULL,
    FOREIGN KEY (transformation_id) REFERENCES transformations(_id) ON DELETE CASCADE,
    FOREIGN KEY (output_block_id) REFERENCES blocks(_id) ON DELETE CASCADE
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO canvo_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO canvo_app;
